---
- hosts: web
  become: yes

  tasks:
   - name: Install latest version of Apache
     apt: name=apache2 update_cache=yes state=latest

   - name: Restart Apache
     service:
       name: apache2
       state: restarted
